### PR TITLE
Update houdini.sql

### PR DESCRIPTION
**Pull request by Blueyzachary**
Change the houdini.sql so that, by default, the basil user is a moderator, so manager can be easily used without modifying the postgreSQL database.

### CODE REVIEW

**Comment by Zaseth** [comment]
This would be insecure as it has a default password.

**Comment by Blueyzachary** [comment]
> This would be insecure as the account has a default password.

Yes, but it would be easier to change the password for basil as well.

**Comment by Zaseth** [comment]
And the chances of someone doing that are small

**Comment by Blueyzachary** [comment]
If it's in the guide, then I think the chances increase

**Comment by Zaseth** [comment]
It's a general best practice not to give default accounts higher privilege.

**Comment by ketnipz** [comment]
See https://github.com/solero/houdini/pull/57

**Pull request closed without merging**
